sudo: required
services:
  - docker
  
 before_install:
  - docker build -t varghesepeter/docker-react -f Dockerfile.dev .
  
script:
  - docker run  varghesepeter/docker-react npm run test -- --coverage
language: generic
